### ISSUE TITLE
Fatal Error: Cannot use positional argument after named argument

### ISSUE THREAD

**Issue by paulrapoza** [backdrop-contrib/views_bulk_operations#19]
I seem to be getting this error 

`"Cannot use positional argument after named argument"...after saving a bulk "Modify Entity values".`

The entity modification works, so the error isn't really stopping me from doing anything, but it's annoying since it's a 500 error :). 

It looks like this may have been addressed on the Drupal 7 version with a patch that's waiting confirmation:
https://www.drupal.org/project/views_bulk_operations/issues/3256781

I'm running PHP 8.1
![184654929-ad929db1-d6ff-4580-8f23-85e9afd7853d](https://user-images.githubusercontent.com/52324937/184657254-8e3f0947-7838-41fe-a069-becf72a1e080.png)
Steps to reproduce: 
1) Install VBO on Backdrop 1.22.2.
2) Do a bulk edit of an entity (mine was a taxonomy term).
3) Type an existing taxonomy term to add to your nodes through entity modification and check "Add new value(s) to Project Types, instead of overwriting the existing values."
4) Action processes successfully but throws the error.

**Comment by argiepiano** [comment]
Thank you for reporting. I'll look into this very soon.

**Comment by paulrapoza** [comment]
> Thank you for reporting. I'll look into this very soon.

I tried the drupal 7-3.x fix and it fixed the error for me. Sadly, it's been like 12 years since I've done a patch but here's the change:

```
--- a/views_bulk_operations.module	
+++ b/views_bulk_operations.module
@@ -806,7 +806,7 @@
 
   // Redirect.
   $query = backdrop_get_query_parameters($_GET, array('q'));
-  $form_state['redirect'] = array('path' => $vbo->view->get_url(), array('query' => $query));
+  $form_state['redirect'] = array($vbo->view->get_url(), array('query' => $query));
 }
 
 /**
```

**Comment by argiepiano** [comment]
Thank you! I've created a PR which I just merged. I'll do a new release soon.
