### ISSUE TITLE
D7 upgrade notices when VBO action doesn't exist in Backdrop 

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/views_bulk_operations#23]
## During the upgrade process itself

The D7 site in question:

 - Uses the D7 "Admin Views" module
 - Has a view that uses only the "Update node alias" operation

These warnings show up in the update process (after all database updates run):

> Warning: Undefined array key "vbo_operations" in views_bulk_operations_update_1000() (line 46 of /app/backdrop/modules/views_bulk_operations/views_bulk_operations.install).

> Warning: foreach() argument must be of type array|object, null given in views_bulk_operations_update_1000() (line 46 of /app/backdrop/modules/views_bulk_operations/views_bulk_operations.install).

## On the site after the upgrade process (likely PHP 8.x issue that can be split out from this)

> Deprecated: Required parameter $context follows optional parameter $entities in /app/backdrop/modules/views_bulk_operations/views_bulk_operations.module on line 1425

**Comment by argiepiano** [comment]
Thanks for reporting, @laryn. Can you check if you have a View with a VBO field, but with no actions selected to be displayed in the selection box of the View? I think that's what's happening here. The update function basically converts existing D7 VBO fields to Backdrop's, but I think I did not anticipate VBO fields with no actions enabled.  

UPDATE: I tried upgrading a D7 site with a VBO with no actions, but am unable to reproduce this warning. Can you add more details to the report?

**Comment by laryn** [comment]
I will try to get more information on this. I was out of time today and just wanted to record it as a starting point but will try to flesh it out more tomorrow. Thanks for looking into it!

**Comment by argiepiano** [comment]
Hi @laryn. 

I believe this is happening because the "Update node alias" action is provided in Pathauto in Drupal 7, and doesn't exist in Backdrop. The equivalent (provided by Bd core) is called "Update content URL alias".   So, the solution is to remove that action from the VBO in your Views in D7, upgrade, and manually add the equivalent in Backdrop.

Still, the update hook should anticipate that there may be some actions that can't be upgraded, and show a warning. I'll check the code to fix that.

**Comment by argiepiano** [comment]
Regarding the deprecated notice: yes, it's a php 8.1 notice. Issue #21  and PR #22. I'll do a release soon.

**Comment by argiepiano** [comment]
@laryn, I've done some testing upgrading D7 with PHP 8.1, with Pathauto and Administration Views enabled, and I can't reproduce the first warnings (the deprecated one is unrelated and there is a PR for that one).

In fact, I thought the custom actions defined by Pathauto were the culprit, but they are not. The update hook simply ignores those actions that don't exist in Bd.

So, the issue must be somewhere else. The only possibility for this to happen is when:
1. There is a View that has a VBO field
2. AND thelist of actions for the field in  `$view->display[DISPLAY_NAME]->display_options['fields']['views_bulk_operations']['vbo_operations']` is empty! 

It almost looks like a bug in your D7 Views, maybe a malformed Views, or an issue with another contrib module. That field definition should never be empty. Any chance you can check which views has an empty VBO field definition?  Try the following with Devel:

```php
$vs = views_get_all_views();
foreach ($vs as $name => $v) {
  $view = views_get_view($name);
  foreach ($view->display as $display_name => $info) {
    if (isset($info->display_options['fields'])) {
      foreach ($info->display_options['fields'] as $field_name => $field_info) {
        if (strpos($field_name, 'views_bulk_operations') === 0) {
          dpm("Found VBO field in View: $name | Display: $display_name");
          if (empty($field_info['vbo_operations'])) {
            dpm("Empty VBO operations found in View: $name | Display: $display_name");
          }
        }
      }
    }
  }
}
```

This code should output issues with VBO fields. Let me know once you do this...

**Comment by argiepiano** [comment]
(Updated the code slightly)

**Comment by argiepiano** [comment]
One additional observation regarding Administration Views (side note, unrelated to the notice): this module doesn't exist in Backdrop. In D7, it creates a new display plugin. So, if you force-save these views into database before upgrading, and then do an upgrade in Backdrop, the resulting upgraded views won't work: they are missing the plugin, and all you can see if you click "Configure" for any of those views is the "Auto preview" functionality of the Views UI.

**Comment by laryn** [comment]
@argiepiano It seems to be coming from the `admin_views_node` view. I'm not sure if they've customized this one or not, and it may well be malformed as you suggest. 

On this site I think I'm content to uninstall `admin_views` completely before the upgrade. If this might occur for others it would be nice to handle it somehow so there are fewer warnings upon upgrade, but if you think it's unlikely to be seen by many others we can simply close this issue.

**Comment by argiepiano** [comment]
@laryn, PR #24 checks for empty `vbo_operations` before looping, just in case. Would you be able to test? After that we can do a release...

**Comment by laryn** [comment]
RTBC!

**Comment by argiepiano** [comment]
Thanks for testing, @laryn!

**Comment by argiepiano** [comment]
Release 1.x-3.0.2 is out!
