### ISSUE TITLE
PHP 8.1 deprecation

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/views_bulk_operations#27]
After updating to 8.1 I get a deprecation warning on my homepage.

Deprecated: Optional parameter $entities declared before required parameter $context is implicitly treated as a required parameter in /var/www/html/modules/contrib/views_bulk_operations/views_bulk_operations.module on line 1424

**Comment by argiepiano** [comment]
Thanks for reporting. This was fixed some time ago in the dev version at #22. I'll do a new release with this fix.
