### ISSUE TITLE
Match version numbering with D7?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/views_bulk_operations#8]
A suggestion for when you do a formal release: match the branch and version for the comparable D7 version. So since D7 is on the `7.x-3.x` branch and current release is `7.x-3.6`, I'd recommend using `1.x-3.x` and `1.x-3.6` for Backdrop, respectively.

**Comment by argiepiano** [comment]
Thanks @laryn. I'll try to rename the dev branch and will also change the release version of the next release to follow that pattern

**Comment by argiepiano** [comment]
I've created branch 1.x-3.x to match D7's dev version and set it as default. Thanks @laryn!
